apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/render
namespace: monitoring
patches:
  - target:
      kind: Alertmanager
    path: patches/single-replica.yaml
  - target:
      kind: Prometheus
    path: patches/single-replica.yaml
  - target:
      kind: Prometheus
    path: patches/prometheus-thanos.yaml
  - target:
      kind: ClusterRoleBinding
      name: prometheus
    path: patches/prometheus-cluster-role-binding-sa.yaml
images:
  - name: quay.io/thanos/thanos
    newTag: v0.31.0
