apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: external-dns
  annotations:
    aadpodidentity.k8s.io/Behavior: namespaced
spec:
  clientID: 2a230695-d99d-4733-8387-171a99d0bae8
  resourceID: /subscriptions/467811c4-023c-4b77-8511-54b5b2eac549/resourceGroups/rg-renovate-talk/providers/Microsoft.ManagedIdentity/userAssignedIdentities/external-dns-operator
  type: 0
