apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: external-dns
  annotations:
    aadpodidentity.k8s.io/Behavior: namespaced
spec:
  clientID: b146a057-c13e-4a44-9e68-13f3180c1705
  resourceID: /subscriptions/467811c4-023c-4b77-8511-54b5b2eac549/resourceGroups/rg-renovate-talk/providers/Microsoft.ManagedIdentity/userAssignedIdentities/external-dns-operator
  type: 0
