apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - trigger-pipelines-task.yaml

configMapGenerator:
  - name: trigger-pipelines-scripts
    files:
      - pvc-template.yaml
      - pod-template.yaml
