apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - "kustomizeconfig"

resources:
  - resources/delegate-rbac.yaml
  - resources/github-eventlistener.yaml
  - resources/github-trigger-ingress.yaml
  - resources/github-trigger-rbac.yaml
  - resources/github-triggerbinding.yaml
  - resources/github-triggertemplate.yaml
  - resources/ns.yaml
  - resources/pipelines/delegate-pipeline.yaml
  - resources/tasks/apply-tekton-task.yaml
  - resources/tasks/create-namespace-task.yaml
  - resources/tasks/trigger-pipelines-task
  - secrets/github-clone-external-secret.yaml
  - secrets/github-trigger-external-secret.yaml

namespace: tekline
