apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterexternalsecrets.external-secrets.io-CustomResourceDefinition.yml
- clustersecretstores.external-secrets.io-CustomResourceDefinition.yml
- external-secrets-Deployment.yml
- external-secrets-ServiceAccount.yml
- external-secrets-cert-controller-ClusterRole.yml
- external-secrets-cert-controller-ClusterRoleBinding.yml
- external-secrets-cert-controller-Deployment.yml
- external-secrets-cert-controller-ServiceAccount.yml
- external-secrets-controller-ClusterRole.yml
- external-secrets-controller-ClusterRoleBinding.yml
- external-secrets-edit-ClusterRole.yml
- external-secrets-leaderelection-Role.yml
- external-secrets-leaderelection-RoleBinding.yml
- external-secrets-view-ClusterRole.yml
- external-secrets-webhook-Deployment.yml
- external-secrets-webhook-Secret.yml
- external-secrets-webhook-Service.yml
- external-secrets-webhook-ServiceAccount.yml
- externalsecret-validate-ValidatingWebhookConfiguration.yml
- externalsecrets.external-secrets.io-CustomResourceDefinition.yml
- secretstore-validate-ValidatingWebhookConfiguration.yml
- secretstores.external-secrets.io-CustomResourceDefinition.yml
