apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/render/

  - resources/azureidentity.yaml
  - resources/azureidentitybinding.yaml
  - resources/ns.yaml
  - resources/secretstore.yaml
  # - resources/test-secret.yaml

patches:
  - target:
      name: external-secrets
      kind: Deployment
      group: apps
      version: v1
    path: patches/azureidentitybinding-label.yaml
namespace: external-secrets
