apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/certmanager-argoapp.yaml
  - resources/externaldns-argoapp.yaml
  - resources/renovate-argoapp.yaml
  - resources/tekline-argoapp.yaml
  - resources/tekton-argoapp.yaml
  - resources/traefik-argoapp.yaml
  # - https://github.com/pietervincken/renovate-talk-microservice-demo.git//argocd?ref=main
  # - https://github.com/pietervincken/renovate-talk-demo-app.git//argocd?ref=main
  - https://github.com/pietervincken/renovate-talk-java-demo-app-deploy.git//argocd?ref=main
