apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: renovate-talk-secret-store

  target:
    name: argocd-secret
    creationPolicy: Owner
    template:
      data:
        webhook.github.secret: "{{ .github_secret }}"
  data:
    - secretKey: github_secret
      remoteRef:
        key: github-trigger-secret
