apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-creds
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store

  target:
    name: github-creds
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: git
        url: git@github.com:pietervincken
        sshPrivateKey: "{{ .ssh_privatekey }}"
  data:
    - secretKey: ssh_privatekey
      remoteRef:
        key: github-private-key
