apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/render/
  - resources/dashboard-ingress.yaml
  - resources/kaniko-azureidentity.yaml
  - resources/kaniko-azureidentitybinding.yaml

patches:
  - target:
      kind: TektonConfig
      name: config
      group: operator.tekton.dev
      version: v1alpha1
    path: patches/dashboard-config.yaml
