apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/render
  - resources/prod-clusterissuer.yaml
  - resources/staging-clusterissuer.yaml

namespace: cert-manager

patches:
  - target:
      kind: Deployment
      name: cert-manager
    path: patches/deployment-leader-election-namespace.yaml

  - target:
      kind: Deployment
      name: cert-manager-cainjector
    path: patches/cainjector-deployment-leader-election-namespace.yaml
