---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-operator-controller-manager
  name: grafana-operator-controller-manager
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: grafana-operator-controller-manager
  strategy: {}
  template:
    metadata:
      labels:
        control-plane: grafana-operator-controller-manager
    spec:
      containers:
        - args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=0.0.0.0:9090
            - --leader-elect
          image: ghcr.io/grafana-operator/grafana-operator:v5.4.1
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          ports:
            - containerPort: 9090
              name: metrics
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /tmp/dashboards
              name: dashboards-dir
      securityContext:
        runAsNonRoot: true
      serviceAccountName: grafana-operator-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - emptyDir: {}
          name: dashboards-dir
