---
# Source: grafana-operator/templates/servicemonitor.yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana-operator
  namespace: "grafana-operator"
  labels:
    app.kubernetes.io/name: grafana-operator
    helm.sh/chart: grafana-operator-3.0.2
    app.kubernetes.io/instance: grafana-operator
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: grafana-operator
    app.kubernetes.io/instance: grafana-operator
