---
# Source: grafana-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-operator-leader-election
  namespace: "grafana-operator"
  labels:
    app.kubernetes.io/name: grafana-operator
    helm.sh/chart: grafana-operator-2.7.25
    app.kubernetes.io/instance: grafana-operator
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana-operator-leader-election
subjects:
  - kind: ServiceAccount
    name: grafana-operator
