---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-operator-controller-manager
  name: grafana-operator-metrics-service
  namespace: grafana
spec:
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: metrics
  selector:
    control-plane: grafana-operator-controller-manager
  type: ClusterIP
