---
# Source: grafana-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-operator
  labels:
    app.kubernetes.io/name: grafana-operator
    helm.sh/chart: grafana-operator-2.7.18
    app.kubernetes.io/instance: grafana-operator
    app.kubernetes.io/managed-by: Helm
roleRef:
  name: grafana-operator
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: grafana-operator
