apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager
spec:
  project: default
  source:
    repoURL: git@github.com:pietervincken/renovate-tekton-argo-talk.git
    targetRevision: 1-create-demo
    path: k8s/certmanager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    {}
    # automated:
    #   prune: true
    #   selfHeal: true
