apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
spec:
  project: default
  source:
    repoURL: git@github.com:pietervincken/renovate-tekton-argo-talk.git
    targetRevision: main
    path: k8s/renovate
  destination:
    server: https://kubernetes.default.svc
    namespace: renovate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
