---
# Source: aad-pod-identity/templates/nmi-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aad-pod-identity-nmi
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad-pod-identity
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity-4.1.11
    app.kubernetes.io/component: nmi
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: ["aadpodidentity.k8s.io"]
    resources: ["azureidentitybindings", "azureidentities", "azurepodidentityexceptions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["aadpodidentity.k8s.io"]
    resources: ["azureassignedidentities"]
    verbs: ["get", "list", "watch"]
