---
# Source: aad-pod-identity/templates/mic-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aad-pod-identity-mic
  namespace: aad-pod-identity
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad-pod-identity
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity-4.1.15
    app.kubernetes.io/component: mic
