---
# Source: aad-pod-identity/templates/mic-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aad-pod-identity-mic
  namespace: aad-pod-identity
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad-pod-identity
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity-4.1.12
    app.kubernetes.io/component: mic
  annotations:
    description: Deploy components for aad-pod-identity
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: aad-pod-identity
      app.kubernetes.io/instance: aad-pod-identity
      app.kubernetes.io/component: mic
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aad-pod-identity
        app.kubernetes.io/instance: aad-pod-identity
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: aad-pod-identity-4.1.12
        app.kubernetes.io/component: mic
      annotations:
        checksum/config: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
    spec:
      serviceAccountName: aad-pod-identity-mic
      containers:
        - name: mic
          image: "mcr.microsoft.com/oss/azure/aad-pod-identity/mic:v1.8.11"
          imagePullPolicy: IfNotPresent
          args:
            - "--cloudconfig=/etc/kubernetes/azure.json"
            - "--logtostderr"
          securityContext:
            runAsUser: 0
            readOnlyRootFilesystem: true
          env:
            - name: MIC_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FORCENAMESPACED
              value: "false"
          volumeMounts:
            - name: k8s-azure-file
              mountPath: /etc/kubernetes/azure.json
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              cpu: 200m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: k8s-azure-file
          hostPath:
            path: /etc/kubernetes/azure.json
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: mic
                topologyKey: kubernetes.io/hostname
              weight: 1
