---
# Source: aad-pod-identity/templates/nmi-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aad-pod-identity-nmi
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad-pod-identity
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity-4.1.15
    app.kubernetes.io/component: nmi
subjects:
  - kind: ServiceAccount
    name: aad-pod-identity-nmi
    namespace: aad-pod-identity
roleRef:
  kind: ClusterRole
  name: aad-pod-identity-nmi
  apiGroup: rbac.authorization.k8s.io
