---
# Source: aad-pod-identity/templates/mic-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aad-pod-identity-mic
  namespace: aad-pod-identity
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad-pod-identity
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity-4.1.11
    app.kubernetes.io/component: mic
  annotations:
    description: Deploy components for aad-pod-identity
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: aad-pod-identity
      app.kubernetes.io/instance: aad-pod-identity
      app.kubernetes.io/component: mic
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aad-pod-identity
        app.kubernetes.io/instance: aad-pod-identity
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: aad-pod-identity-4.1.11
        app.kubernetes.io/component: mic
      annotations:
        checksum/config: cf4ae26b548b324d3b3b7a77e4b1ab0b2a7b4439fe052a5ec16c9da191c9cb5e
    spec:
      serviceAccountName: aad-pod-identity-mic
      containers:
        - name: mic
          image: "mcr.microsoft.com/oss/azure/aad-pod-identity/mic:v1.8.10"
          imagePullPolicy: IfNotPresent
          args:
            - "--logtostderr"
          securityContext:
            readOnlyRootFilesystem: true
          env:
            - name: MIC_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FORCENAMESPACED
              value: "true"
            - name: CLOUD
              valueFrom:
                secretKeyRef:
                  key: Cloud
                  name: aad-pod-identity-mic
            - name: SUBSCRIPTION_ID
              valueFrom:
                secretKeyRef:
                  key: SubscriptionID
                  name: aad-pod-identity-mic
            - name: RESOURCE_GROUP
              valueFrom:
                secretKeyRef:
                  key: ResourceGroup
                  name: aad-pod-identity-mic
            - name: VM_TYPE
              valueFrom:
                secretKeyRef:
                  key: VMType
                  name: aad-pod-identity-mic
            - name: TENANT_ID
              valueFrom:
                secretKeyRef:
                  key: TenantID
                  name: aad-pod-identity-mic
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: ClientID
                  name: aad-pod-identity-mic
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: ClientSecret
                  name: aad-pod-identity-mic
            - name: USE_MSI
              valueFrom:
                secretKeyRef:
                  key: UseMSI
                  name: aad-pod-identity-mic
            - name: USER_ASSIGNED_MSI_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: UserAssignedMSIClientID
                  name: aad-pod-identity-mic
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              cpu: 200m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 256Mi
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: mic
                topologyKey: kubernetes.io/hostname
              weight: 1
