---
# Source: aad-pod-identity/templates/mic-exception.yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzurePodIdentityException
metadata:
  name: mic
  namespace: aad-pod-identity
spec:
  podLabels:
    app: mic
    component: mic
    app.kubernetes.io/component: mic
