apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: renovate-talk-secret-store
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      # identityId: "external-secrets-operator"
      vaultUrl: "https://kvrenovate-talk.vault.azure.net/"
