apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- config-TektonConfig.yml
- config-logging-ConfigMap.yml
- tekton-config-defaults-ConfigMap.yml
- tekton-config-observability-ConfigMap.yml
- tekton-config-read-role-ClusterRole.yml
- tekton-config-read-rolebinding-ClusterRoleBinding.yml
- tekton-operator-ClusterRole.yml
- tekton-operator-ClusterRoleBinding.yml
- tekton-operator-Deployment.yml
- tekton-operator-Namespace.yml
- tekton-operator-Service.yml
- tekton-operator-ServiceAccount.yml
- tekton-operator-info-ConfigMap.yml
- tekton-operator-info-Role.yml
- tekton-operator-info-RoleBinding.yml
- tekton-operator-webhook-Deployment.yml
- tekton-operator-webhook-Service.yml
- tekton-operator-webhook-certs-Secret.yml
- tekton-result-read-role-ClusterRole.yml
- tekton-result-read-rolebinding-ClusterRoleBinding.yml
- tektonchains.operator.tekton.dev-CustomResourceDefinition.yml
- tektonconfigs.operator.tekton.dev-CustomResourceDefinition.yml
- tektondashboards.operator.tekton.dev-CustomResourceDefinition.yml
- tektonhubs.operator.tekton.dev-CustomResourceDefinition.yml
- tektoninstallersets.operator.tekton.dev-CustomResourceDefinition.yml
- tektonpipelines.operator.tekton.dev-CustomResourceDefinition.yml
- tektonresults.operator.tekton.dev-CustomResourceDefinition.yml
- tektontriggers.operator.tekton.dev-CustomResourceDefinition.yml
namespace: tekton-operator
