---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator.tekton.dev/release: v0.68.1
    version: v0.68.1
  name: tekton-operator-webhook
  namespace: tekton-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tekton-operator-webhook
  template:
    metadata:
      labels:
        app: tekton-operator
        name: tekton-operator-webhook
    spec:
      containers:
        - env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_LOGGING_NAME
              value: config-logging
            - name: WEBHOOK_SERVICE_NAME
              value: tekton-operator-webhook
            - name: WEBHOOK_SECRET_NAME
              value: tekton-operator-webhook-certs
            - name: METRICS_DOMAIN
              value: tekton.dev/operator
          image: gcr.io/tekton-releases/github.com/tektoncd/operator/cmd/kubernetes/webhook:v0.68.1@sha256:7a015c6f820e29fd0a4627e21c16d5111da48086fe43df1d7e6673c7216fd700
          name: tekton-operator-webhook
          ports:
            - containerPort: 8443
              name: https-webhook
      serviceAccountName: tekton-operator
