---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator.tekton.dev/release: v0.60.0
    version: v0.60.0
  name: tekton-operator
  namespace: tekton-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tekton-operator
  template:
    metadata:
      labels:
        app: tekton-operator
        name: tekton-operator
    spec:
      containers:
        - args:
            - -controllers
            - tektonconfig,tektonpipeline,tektontrigger,tektonhub,tektonchain,tektonresults,tektondashboard
            - -unique-process-name
            - tekton-operator-lifecycle
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: tekton-operator
            - name: IMAGE_PIPELINES_PROXY
              value: gcr.io/tekton-releases/github.com/tektoncd/operator/cmd/kubernetes/proxy-webhook:v0.60.0@sha256:09fb2b1a97bcd4cb3f0278cec0ece101aeacb59b2253045a4b971e3ac880a6c0
            - name: IMAGE_JOB_PRUNER_TKN
              value: gcr.io/tekton-releases/dogfooding/tkn@sha256:025de221fb059ca24a3b2d988889ea34bce48dc76c0cf0d6b4499edb8c21325f
            - name: METRICS_DOMAIN
              value: tekton.dev/operator
            - name: VERSION
              value: v0.60.0
            - name: CONFIG_OBSERVABILITY_NAME
              value: tekton-config-observability
            - name: AUTOINSTALL_COMPONENTS
              valueFrom:
                configMapKeyRef:
                  key: AUTOINSTALL_COMPONENTS
                  name: tekton-config-defaults
            - name: DEFAULT_TARGET_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  key: DEFAULT_TARGET_NAMESPACE
                  name: tekton-config-defaults
          image: gcr.io/tekton-releases/github.com/tektoncd/operator/cmd/kubernetes/operator:v0.60.0@sha256:22ca40497d6f820d6b2034905f30d9c13fc46cc3e113dadbe332d00656648a70
          imagePullPolicy: Always
          name: tekton-operator-lifecycle
        - args:
            - -controllers
            - tektoninstallerset
            - -unique-process-name
            - tekton-operator-cluster-operations
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: tekton-operator
            - name: PROFILING_PORT
              value: "9009"
            - name: VERSION
              value: v0.60.0
          image: gcr.io/tekton-releases/github.com/tektoncd/operator/cmd/kubernetes/operator:v0.60.0@sha256:22ca40497d6f820d6b2034905f30d9c13fc46cc3e113dadbe332d00656648a70
          imagePullPolicy: Always
          name: tekton-operator-cluster-operations
      serviceAccountName: tekton-operator
