---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator.tekton.dev/release: v0.64.0
    version: v0.64.0
  name: tekton-operator
  namespace: tekton-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tekton-operator
  template:
    metadata:
      labels:
        app: tekton-operator
        name: tekton-operator
    spec:
      containers:
        - args:
            - -controllers
            - tektonconfig,tektonpipeline,tektontrigger,tektonhub,tektonchain,tektonresults,tektondashboard
            - -unique-process-name
            - tekton-operator-lifecycle
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: tekton-operator
            - name: IMAGE_PIPELINES_PROXY
              value: gcr.io/tekton-releases/github.com/tektoncd/operator/cmd/kubernetes/proxy-webhook:v0.64.0@sha256:a3418b35b62f4b13d109c01e66e3263f0b5509b854a53eb1c81844bfbb2adc58
            - name: IMAGE_JOB_PRUNER_TKN
              value: gcr.io/tekton-releases/dogfooding/tkn@sha256:025de221fb059ca24a3b2d988889ea34bce48dc76c0cf0d6b4499edb8c21325f
            - name: METRICS_DOMAIN
              value: tekton.dev/operator
            - name: VERSION
              value: v0.64.0
            - name: CONFIG_OBSERVABILITY_NAME
              value: tekton-config-observability
            - name: AUTOINSTALL_COMPONENTS
              valueFrom:
                configMapKeyRef:
                  key: AUTOINSTALL_COMPONENTS
                  name: tekton-config-defaults
            - name: DEFAULT_TARGET_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  key: DEFAULT_TARGET_NAMESPACE
                  name: tekton-config-defaults
          image: gcr.io/tekton-releases/github.com/tektoncd/operator/cmd/kubernetes/operator:v0.64.0@sha256:cc1736b7a78aa36d13644978758590c6fd0a6eb73fcaf02c35e53ed973bb305f
          imagePullPolicy: Always
          name: tekton-operator-lifecycle
        - args:
            - -controllers
            - tektoninstallerset
            - -unique-process-name
            - tekton-operator-cluster-operations
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: tekton-operator
            - name: PROFILING_PORT
              value: "9009"
            - name: VERSION
              value: v0.64.0
            - name: METRICS_DOMAIN
              value: tekton.dev/operator
          image: gcr.io/tekton-releases/github.com/tektoncd/operator/cmd/kubernetes/operator:v0.64.0@sha256:cc1736b7a78aa36d13644978758590c6fd0a6eb73fcaf02c35e53ed973bb305f
          imagePullPolicy: Always
          name: tekton-operator-cluster-operations
      serviceAccountName: tekton-operator
