apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/render
- resources/azureidentity.yaml
- resources/azureidentitybinding.yaml
- resources/ns.yaml

images:
- name: k8s.gcr.io/external-dns/external-dns
  newTag: v0.12.2

patches:
- path: patches/deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: external-dns
    version: v1

secretGenerator:
- files:
  - secrets/azure.json
  name: azure-config-file

namespace: external-dns
