apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/deployment.yaml
  - resources/secret.yaml

configMapGenerator:
  - name: renovate-config
    files:
      - configs/config.json

namespace: renovate
