apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/cronjob.yaml
  - resources/ns.yaml
  - resources/sa.yaml
  - secrets/renovate-external-secret.yaml

configMapGenerator:
  - name: renovate-config
    files:
      - configs/config.json

namespace: renovate
