apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/render
  - resources/ns.yaml

patches:
  - target:
      kind: Ingress
      name: grafana
    path: patches/ingress-host.yaml
