apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/certmanager-argoapp.yaml
  - resources/externaldns-argoapp.yaml
  - resources/ingress.yaml
  - resources/render/
  - resources/renovate-argoapp.yaml
  - resources/tekline-argoapp.yaml
  - resources/tekton-argoapp.yaml
  - resources/traefik-argoapp.yaml
  - secrets/argocd-secret-externalsecret.yaml
  - secrets/githubcredentials-externalsecret.yaml
  # - https://github.com/pietervincken/renovate-talk-microservice-demo.git//argocd?ref=main
  # - https://github.com/pietervincken/renovate-talk-demo-app.git//argocd?ref=main
  - https://github.com/pietervincken/renovate-talk-java-demo-app-deploy.git//argocd?ref=main
namespace: argocd

patches:
  - target:
      kind: Deployment
      group: apps
      version: v1
      name: argocd-server
    path: patches/deployment.yaml

  - target:
      kind: ConfigMap
      name: argocd-cm
    path: patches/configmap.yaml

replicas:
  - name: argocd-dex-server
    count: 0
