apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/ns.yaml
- resources/render/applications.argoproj.io.yml
- resources/render/applicationsets.argoproj.io.yml
- resources/render/appprojects.argoproj.io.yml
- resources/render/argocd-application-controller-network-policy.yml
- resources/render/argocd-application-controller.yml
- resources/render/argocd-applicationset-controller.yml
- resources/render/argocd-cm.yml
- resources/render/argocd-cmd-params-cm.yml
- resources/render/argocd-dex-server-network-policy.yml
- resources/render/argocd-dex-server.yml
- resources/render/argocd-gpg-keys-cm.yml
- resources/render/argocd-metrics.yml
- resources/render/argocd-notifications-cm.yml
- resources/render/argocd-notifications-controller-metrics.yml
- resources/render/argocd-notifications-controller.yml
- resources/render/argocd-notifications-secret.yml
- resources/render/argocd-rbac-cm.yml
- resources/render/argocd-redis-network-policy.yml
- resources/render/argocd-redis.yml
- resources/render/argocd-repo-server-network-policy.yml
- resources/render/argocd-repo-server.yml
- resources/render/argocd-secret.yml
- resources/render/argocd-server-metrics.yml
- resources/render/argocd-server-network-policy.yml
- resources/render/argocd-server.yml
- resources/render/argocd-ssh-known-hosts-cm.yml
- resources/render/argocd-tls-certs-cm.yml
- resources/render/ns.yaml
