apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/ingress.yaml
  - resources/render/
  - secrets/argocd-secret-externalsecret.yaml
  - secrets/githubcredentials-externalsecret.yaml
namespace: argocd

patches:
  - target:
      kind: Deployment
      group: apps
      version: v1
      name: argocd-server
    path: patches/deployment.yaml

  - target:
      kind: ConfigMap
      name: argocd-cm
    path: patches/configmap.yaml

replicas:
  - name: argocd-dex-server
    count: 0
