apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/render
  - resources/ns.yaml
  - resources/stripprefix-middleware.yaml

patches:
  - target:
      kind: Service
      name: traefik
    path: patches/service.yaml

  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: traefik-ingress-controller
    path: patches/clusterrolebinding-ns.yaml

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: traefik
    path: patches/deployment.yaml
namespace: traefik
