apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-trigger-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store

  target:
    name: es-github-trigger-secret
    creationPolicy: Owner

  data:
    - secretKey: secretToken
      remoteRef:
        key: github-trigger-secret # name is secret store (AWS secrets manager or Azure Key Vault)
