apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-clone-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store

  target:
    name: es-github-clone
    creationPolicy: Owner
    template:
      metadata:
        labels:
          tekline.joyrex2001.com/sync-to-delegate: "true" # make sure the ssh credential is passed to the target namespace for cloning.
        annotations:
          tekton.dev/git-0: github.com
      type: kubernetes.io/ssh-auth
      data:
        ssh-privatekey: "{{ .ssh_privatekey }}"
        known_hosts: "{{ .known_hosts }}"

  data:
    - secretKey: ssh_privatekey
      remoteRef:
        key: github-private-key

    - secretKey: known_hosts
      remoteRef:
        key: github-known-hosts
