apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-trigger-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: renovate-talk-secret-store

  target:
    name: es-github-trigger-secret
    creationPolicy: Owner

  data:
    # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
    - secretKey: secretToken
      remoteRef:
        key: github-trigger-secret
