apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: kaniko
  annotations:
    aadpodidentity.k8s.io/Behavior: namespaced
spec:
  clientID: 745f8dc0-b375-48ad-9a12-7a0488652b20
  resourceID: /subscriptions/467811c4-023c-4b77-8511-54b5b2eac549/resourceGroups/rg-renovate-talk/providers/Microsoft.ManagedIdentity/userAssignedIdentities/kaniko
  type: 0
