apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - create-namespace-task.yaml

configMapGenerator:
  - name: create-namespace-scripts
    files:
      - sa.yaml
  - name: create-namespace-resources
