- op: add
  path: /data
  value:
    resource.exclusions: |
      - apiGroups:
          - tekton.dev
        kinds:
          - PipelineRun
        clusters:
          - https://kubernetes.default.svc
      - apiGroups:
          - tekton.dev
        kinds:
          - TaskRun
        clusters:
          - https://kubernetes.default.svc
